### ISSUE TITLE
Some tests fail on aarch64

### ISSUE THREAD

**Issue by ggardet** [simonmar/alex#130]
On AArch64, I need to remove all tests after ```tokens.x``` from Makefile: 
```tokens_bytestring.x 
tokens_bytestring_unicode.x 
tokens_monad_bytestring.x
tokens_monadUserState_bytestring.x
tokens_posn.x tokens_posn_bytestring.x 
tokens_scan_user.x 
tokens_strict_bytestring.x
unicode.x
```
because of hanging ghc for ```*.g.hs``` (```*.n.hs``` are fine)
Example of hanging commands:
```ghc -Wall -fno-warn-missing-signatures -fno-warn-unused-imports -fno-warn-tabs -Werror -package array -package bytestring  tokens_monad_bytestring.g.hs -o tokens_monad_bytestring.g.bin```

What is strange is, if I remove ```tokens.x```, then next test (```tokens_bytestring.x```) succeeds, but the one after still fails.
Any idea what's going on?

**Comment by simonmar** [comment]
No idea I'm afraid. But perhaps this is a GHC bug and not an Alex bug? I suggest opening a ticket at https://ghc.haskell.org/trac/ghc with the example code that causes the compiler to hang.
