### ISSUE TITLE
ghc-8.8.x can't compile default_typeclass.n.hs

### ISSUE THREAD

**Issue by peti** [simonmar/alex#140]
ghc-8.8.1-alpha-2 cannot compile the `alex-3.2.4` test suite:

~~~
    default_typeclass.x:285:5: error:
        ‘fail’ is not a (visible) method of class ‘Monad’
        |
    285 |     fail str = StateT $ \_ -> fail str
        |     ^^^^
    make: *** [Makefile:61: default_typeclass.n.bin] Error 1
    /home/abuild/rpmbuild/BUILDROOT/alex-3.2.4-ghc88.1.2.x86_64/usr/bin/alex  -g default_typeclass.x -o default_typeclass.g.hs
    ghc -Wall -fno-warn-missing-signatures -fno-warn-unused-imports -fno-warn-tabs -Werror -package array -package bytestring  default_typeclass.g.hs -o default_typeclass.g.bin
    [1 of 1] Compiling Main             ( default_typeclass.g.hs, default_typeclass.g.o )
    
    default_typeclass.x:285:5: error:
        ‘fail’ is not a (visible) method of class ‘Monad’
        |
    285 |     fail str = StateT $ \_ -> fail str
        |     ^^^^
    make: *** [Makefile:61: default_typeclass.g.bin] Error 1
~~~

**Comment by peti** [comment]
Ping?

**Comment by luc-tielen** [comment]
Can a (patch?) release be made for this?

**Comment by cdepillabout** [comment]
@grahamcofborg eval

**Comment by peti** [comment]
Ping?

A new release that contains this fix would be really nice! Currently, distributors that want to use ghc-8.8.1 are spending lots of time, wondering about the problem, googling, eventually finding the ticket on Github, manually applying the patch to their distribution, and testing the modified package.  This is a very inefficent use of resources. :-(

If time constraints don't allow making the new release right now, then I'd volunteer to do it. I'd need upload access to Hackage, obviously, then I could release a fixed version.

**Comment by simonmar** [comment]
Done
