### ISSUE TITLE
Is this long columns of ints expected behaviour on the example?

### ISSUE THREAD

**Issue by step21** [simonmar/alex#161]
I am just playing around with haskell and alex. When running the example from the docs, the resulting .hs file has superfluous whitespace like a snowy mountain and long columns of integers, why? Is it some kind of test? In the closest comment it says 'GScan wrapper', whatever that means.
Maybe I just do not know enough haskell, but any insight would be great. Google and docs didn't help so far.

**Comment by andreasabel** [comment]
> has superfluous whitespace like a snowy mountain

I suppose no one cared to make the output look nice, since it is only for consumption by the Haskell compiler.

> long columns of integers

If I am not mistaken, these integers represent the transition table of the generated automaton.

**Comment by step21** [comment]
Thanks for clarifying, that makes sense. However I thought that as it is supposed to be usable for lexer/parser generation, I actually need to know what it is doing.

**Comment by andreasabel** [comment]
Content of this issue duplicates #84 and #105.
