### ISSUE TITLE
Release for GHC 9.0.1

### ISSUE THREAD

**Issue by vmchale** [simonmar/alex#162]
It appears that the version of alex on hackage breaks on GHC 9.0.1 (alpha 1)

However, it doesn't have any problems with the code in this repo, so I think all that is needed is a new release to hackage.

Thanks!

**Comment by GeorgeCo** [comment]
When I do  cabal install alex --allow-new with
 ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.0.20200925
I get the following error:
...
[20 of 22] Compiling DFAMin           ( src/DFAMin.hs, dist/build/alex/alex-tmp/DFAMin.o )

src/DFAMin.hs:35:17: error:
    Suffix occurrence of @. For an as-pattern, remove the leading whitespace.
   |
35 | minimizeDFA  dfa@ DFA { dfa_start_states = starts,
   |                 ^
cabal: Failed to build exe:alex from alex-3.2.5. See the build log above for
details.

**Comment by andreasabel** [comment]
Close this issue? 
Seems to be fixed by 33331a98ab89f5207fcf3a61977f1db3ead229a4 and the release of 3.2.6.

**Comment by Ericson2314** [comment]
Yes 3.2.6 should work for `9.0`. It does not currently work `master`, but that is supposed to be fixed with once https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492 is merged after which 3.2.6 will work for all versions.
