### ISSUE TITLE
Haddocks on hackage

### ISSUE THREAD

**Issue by Boarders** [simonmar/alex#191]
Is there a reason that there is no available Haddock documentation for the internals of Alex? I find it very annoying to figure out what monad the various wrappers give you access to but not always easy to look up.

**Comment by andreasabel** [comment]
Alex is an executable-only package and these do not have Haddockumentation on Hackage.  
The documentation might be lacking (see e.g. #128), so suggestions/PRs for documentation improvement are welcome.

OP is answered, so I am closing this.  Feel free to reopen if there is new information to consider.
