### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by athas** [simonmar/alex#196]
Could we get a new release on Hackage please?  Commits such as 0eec6193df0a36b94709e3d4751648023edd262e are needed for Alex to work on GHC HEAD.

Unfortunately we cannot just use `source-repository-package` in our `cabal.project` to include this repository, because of the manual bootstrapping shenanigans that are needed to prepare an sdist for Alex.

**Comment by Ericson2314** [comment]
Can you try out https://hackage.haskell.org/package/alex-3.2.7/candidate/ and let me know how it goes?

**Comment by athas** [comment]
I can build that one with GHC HEAD.  I can also build it with GHC 8.10.7, so it's probably good!

**Comment by Ericson2314** [comment]
Thanks!
