### ISSUE TITLE
Problem with NUL character.

### ISSUE THREAD

**Issue by jdgallag84** [simonmar/alex#24]
I cannot seem to lex the Null character in a string.  I would like to have a lexer that can read the string 
"ab\NULcd"
However, no matter what I tried, when running the lexer I get Lexical error.

Here is my definition

$escchars = [abfnrtv\\"\'&]
@escape = \ ($escchars | \NUL)
@gap = \ $white+ \
@string = $printable # [\"\] | " " | @escape | @gap

I would like to do

\" string\* \"  {\s -> String (strip s)}

(where strip removes the beginning and trailing ")

I have tried all kind of things for doing the null character from just NUL to \0 to 0, ... to copying Marlow's example definition of the ASCII characters, and nothing works.  I always get a lexical error when trying to lex a file with a string with the NUL character in it.

Please help.  Thank you!!

**Comment by andreasabel** [comment]
As far as I can tell, there is no problem with NUL.
@simonmar, please close.
