### ISSUE TITLE
Strange Alex warnings, ghc 7.11, cabal 1.22.0.1

### ISSUE THREAD

**Issue by Skyfold** [simonmar/alex#61]
Everything compiles fine and works as far a I can tell, but I didn't have the 20+ lines of warnings before ghc 7.10. Just a heads up.

[3 of 5] Compiling Token            ( dist/build/verifier/verifier-tmp/Token.hs, dist/build/verifier/verifier-tmp/Token.o )

dist/build/verifier/verifier-tmp/Token.hs:391:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:392:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:393:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:397:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:398:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:402:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:404:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:408:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:410:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:414:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:423:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:437:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:439:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:440:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:441:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:443:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:444:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:445:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:446:5: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:448:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:451:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:452:1: Warning:
    Tab character

dist/build/verifier/verifier-tmp/Token.hs:453:1: Warning:
    Tab character

**Comment by simonmar** [comment]
Fixed in 8dad5baf2533380514c1518ae7dd3736865b54a2
