### ISSUE TITLE
Test suite failure on GHC 7.10

### ISSUE THREAD

**Issue by snoyberg** [simonmar/alex#62]
Full log at: https://gist.github.com/snoyberg/7116b7d9a78cf486c675

**Comment by simonmar** [comment]
Fixed in b1472bfbb7b95bcd6c66558197e2603997d9ce0b

**Comment by snoyberg** [comment]
Can you ping me when this is on Hackage so I can update the Stackage constraints?

**Comment by juhp** [comment]
Apparently fixed in 1.3.5 (see fpco/stackage#1006)
