### ISSUE TITLE
token length incorrect using --latin1 option

### ISSUE THREAD

**Issue by chrismshelton** [simonmar/alex#63]
The template files assume UTF-8 in the `alex_scan_tkn` function, even when the --latin1 option is given.

In [templates/GenericTemplate.hs](https://github.com/simonmar/alex/blob/master/templates/GenericTemplate.hs#L178):
```haskell
alex_scan_tkn user orig_input (if c < 0x80 || c >= 0xC0 then PLUS(len,ILIT(1)) else len)
```

This leads to an incorrect length being given to the lexer actions for tokens containing bytes between 0x80 and 0xC0

**Comment by hvr** [comment]
do you happen to have a small test-case for this?

**Comment by chrismshelton** [comment]
Sorry, my bad, now that I'm trying to come up with a test case I can't reproduce the error
