### ISSUE TITLE
Add support for `{-# OPTIONS_ALEX ... #-}` pragma

### ISSUE THREAD

**Issue by hvr** [simonmar/alex#66]
The motivation is that e.g. `alex-options: --latin1` can't be set in `.cabal` files, but if we had a way to set `alex` options directly in `.x`-files, we could workaround more easily...

**Comment by chamini2** [comment]
This is a great idea (unless there's already a way to get it working), but should the options be in *Haskell code* (between braces) or in *Alex code*?

In Alex code we could use a different syntax, maybe at the beginning of the file.

**Comment by hvr** [comment]
As far as I'm concerned, the motivation I had for bringing up this feature request has been addressed via #81, so I'm closing this
