### ISSUE TITLE
Cabal/ Stack build creates bad AlexWrapper-monad-bytestring

### ISSUE THREAD

**Issue by dfordivam** [simonmar/alex#73]
The hackage 'cabal' / stackage build looks bad/ broken with respect to 'AlexWrapper-monad-bytestring'
These files don't contain the 'instance Applicative'

~/.stack/snapshots/x86_64-linux/lts-3.14/7.10.2/share/x86_64-linux-ghc-7.10.2/alex-3.1.4/AlexWrapper-monad-bytestring
~/.cabal/share/x86_64-linux-ghc-7.8.4/alex-3.1.4/AlexWrapper-monad-bytestring

I tried a local build of alex with the latest source code from github and it *does* contain the Applicative instance. So I am not sure where the issue might be.

**Comment by dfordivam** [comment]
I have found a work around and included it here http://stackoverflow.com/questions/33758728/alex-wrappers-hs-no-instance-of-applicative

**Comment by amnn** [comment]
The `monad-bytestring` wrapper, as found in the Hackage release also has incorrect type signatures which causes a compilation error too (for me). This has also been fixed in HEAD: #65

**Comment by simonmar** [comment]
I just uploaded 3.1.5 to Hackage which should fix this.
