### ISSUE TITLE
alex-3.1.5 doesn't declare its dependency on happy

### ISSUE THREAD

**Issue by peti** [simonmar/alex#75]
Citing from http://hydra.cryp.to/build/1389306/nixlog/1/raw:

~~~
Building alex-3.1.5...
Preprocessing executable 'alex' for alex-3.1.5...
Setup: The program 'happy' is required but it could not be found
~~~~

Apparently a `build-tools: happy` attribute is missing from the Cabal file.

**Comment by peti** [comment]
And while I am at it ... `perl` seems to be missing, too.

**Comment by simonmar** [comment]
Sigh, `alex` is not supposed to depend on Happy because it comes with the Happy-generated files.  But this functionality in Cabal seems to break all the time.  Let me check and see what happened.

**Comment by simonmar** [comment]
Uploaded 3.1.6 without the problem, and filed an issue with cabal: https://github.com/haskell/cabal/issues/2940

**Comment by hvr** [comment]
Cabal should have never attempted to regenerate the parsers if `build-tools: happy` is not specified

**Comment by simonmar** [comment]
Do you mean "should" as in "it doesn't behave like that right now, but someone should fix it", or "I believe it behaves like that now, so if it doesn't it's a bug"?

If Cabal never runs Happy unless `build-tools: happy` is present, then I would need to have a `-f devel` flag to alex to enable the `build-tools: happy` line when modifying the parser or building the source distribution.
