### ISSUE TITLE
Release 3.1.5 seems to have caused breakage

### ISSUE THREAD

**Issue by snoyberg** [simonmar/alex#78]
The example I'm seeing in Stackage is:

https://github.com/mainland/language-c-quote/issues/57

Were there any changes to alex that would explain this?

**Comment by Athas** [comment]
The reason for this is that `Data.Char.ord` is no longer implicitly available in the generated code.  I wouldn't say this is an error in alex - the lexer should never have assumed that it was available (and indeed it can be fixed by just importing it manually).

**Comment by snoyberg** [comment]
It's a breaking change in behavior. Whether the behavior was intentional or not is irrelevant; code that previously compiled does not, making this a breaking change.

**Comment by simonmar** [comment]
Yes, the change snuck in without me noticing.  But since it's arguably more correct for Alex to not pollute the namespace with things it needs, I'm inclined to leave it as it is rather than change it back.  It's not hard to fix, and the fix is backwards compatible.

**Comment by Athas** [comment]
Simon Marlow <notifications@github.com> writes:

> Yes, the change snuck in without me noticing.  But since it's arguably
> more correct for Alex to not pollute the namespace with things it
> needs, I'm inclined to leave it as it is rather than change it back.
> It's not hard to fix, and the fix is backwards compatible.

It looks like alex-generated code still contains some namespace
pollution, notably importing all of Data.Array and GHC.Exts.  Perhaps it
could be considered to import all modules as qualified, to prevent
lexers from depending on implementation details in the future?

-- 
\  Troels
/\ Henriksen

**Comment by simonmar** [comment]
Sure - but Alex is in maintenance mode, I accept pull requests and make Hackage releases but I don't do any significant work on it myself.

**Comment by peti** [comment]
Just out of academic curiosity: do we consider the removal of the previously exported `ord` function an API change or not? If it is, then the new release ought to be dubbed version 3.2 (or higher).
