### ISSUE TITLE
Factor out QuickCheck dep into only being required for the test suite?

### ISSUE THREAD

**Issue by gbaz** [simonmar/alex#87]
I don't know how tricky this may be, but as it stands, having alex as a whole require QuickCheck makes things somewhat tricky for the new minimal platform, and we have to hack around it in silly ways. If it isn't a ridiculous hassle, it would be nice for QuickCheck to be only required when building the tests?

**Comment by simonmar** [comment]
Fixed, QuickCheck is no longer required unless you use `-f quickcheck`.
